language: python


python:
- '3.7'
sudo: false

install:
- pip3 install pipenv
- git clone git+https://github.com/schultzm/ARBanker.git
- cd ARBanker
- pipenv install .

before_script:
- pip3 install codecov
script:
- coverage run setup.py test

after_success:
- codecov
