language: python
addons:
  apt:
    packages:
python:
- '3.7'
sudo: false

install:
- pip3 install git+https://github.com/schultzm/ARBanker.git\

before_script:
- pip3 install codecov
script:
- coverage run setup.py test
after_success:
- codecov
